version: "3"

services:
  automation-tests:
    build: .
    container_name: selenium_framework_tests
    volumes:
      - .:/app
    working_dir: /app
    command: bash -c "mkdir -p reports/allure-results && pytest -v --alluredir=reports/allure-results"